project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from web import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web.urls',namespace='web')),
    # path('blog',include('blog.urls',namespace='blog')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
admin.site.site_header = "PROJECT Administration"
admin.site.site_title = "PROJECT Admin Portal"
admin.site.index_title = "Welcome to PROJECT Admin Portal"

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index,name="index"),
    path('index-2/', views.index_2,name="index_2"),
    path('about/', views.about,name="about"),
    path('blog/', views.blog,name="blog"),
    path('blog-right/', views.blogright,name="blogright"),
    path('blog-left/', views.blogleft,name="blogleft"),
    path('checkout/', views.checkout,name="checkout"),
    path('contact/', views.contact,name="contact"),
    path('wishlist/', views.wishlist,name="wishlist"),
    path('news/', views.news,name="news"),
    path('shop-left/', views.shopleft,name="shopleft"),
    path('shop-detalis/', views.shopdetalis,name="shopdetalis"),
    path('shop-detalis-left/', views.shopdetalisleft,name="shopdetalisleft"),
    path('shop-detalis-right/', views.shopdetalisright,name="shopdetalisright"),
    path('shopping-cart/', views.shoppingcart,name="shoppingcart"),
    path('shopgrid-left/', views.shopgridleft,name="shopgridleft"),
    path('shopgrid-right/', views.shopgridright,name="shopgridright"),
    path('shopgrid/', views.shopgrid,name="shopgrid"),
    path('shoplist/', views.shoplist,name="shoplist"),
    path('shoplist-right/', views.shoplistright,name="shoplistright"),
    path('shoplist-left/', views.shoplistleft,name="shoplistleft"),
    path('404/', views.error,name="error"),
]

web/models.py
from email.mime import image
from django.db import models
from versatileimagefield.fields import VersatileImageField


COLOR_CHOICES = (
    ("Red","Red"), ("Blue","Blue"), ("Yellow","Yellow"), ("Orange","Orange"),
)
SIZE_CHOICES = (
    ("XL","Xtra_Large"), ("L","Large"), ("M","Medium"), ("S","Small"), ("XS","Xtra_Small"),
)
class Category(models.Model):
    title = models.CharField(max_length=200)
    image =  VersatileImageField(blank=True, null=True)
    slug = models.SlugField(max_length=200,blank=True,null=True,unique=True)
    class Meta:
        ordering = ("-title","id")
        verbose_name = ('Category')
        verbose_name_plural = ('Categories')
    def __str__(self):
        return f"{self.title}"
class Department(models.Model):
    name = models.CharField(max_length=200)
    class Meta:
        ordering = ("-name","id")
    def __str__(self):
        return f"{self.name}"
class Product(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category,on_delete=models.PROTECT,blank=True,null=True)
    color = models.CharField(max_length=200,choices=COLOR_CHOICES)
    size = models.CharField(max_length=200, choices=SIZE_CHOICES)
    weight = models.CharField(max_length=200)
    photo = VersatileImageField()
    cost = models.DecimalField(max_digits=5, decimal_places=2)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    mrp = models.DecimalField(max_digits=5, decimal_places=2)
    stock = models.IntegerField()
    description = models.TextField(blank=True, null=True)
    meta_description = models.TextField(blank=True, null=True)
    additional_info = models.TextField(blank=True, null=True )

    class Meta:
        ordering = ("-title","id")
    def __str__(self):
        return f"{self.title}" 

    def get_price(self):
        return f"&#8377; {self.price}"

# class Customer(models.Model):
#     first_name = models.CharField(max_length=200)
#     last_name = models.CharField(max_length=200)
#     email = models.EmailField(unique=True)
#     phone = models.CharField(max_length=200)
#     birth_date = models.DateField(null=True)

# class Order(models.Model):
#     PAYMENT_STATUS_PENDING = 'P'
#     PAYMENT_STATUS_COMPLETE = 'C'
#     PAYMENT_STATUS_FAILED = 'F'

#     PAYMENT_STATUS_CHOICES = [
#         (PAYMENT_STATUS_PENDING, 'Pending'),
#         (PAYMENT_STATUS_COMPLETE, 'Complete'),
#         (PAYMENT_STATUS_FAILED, 'Failed'),
#     ]

#     placed_at = models.DateTimeField(auto_now_add=True)
#     payment_status = models.CharField(max_length=1, choices=PAYMENT_STATUS_CHOICES, default=PAYMENT_STATUS_PENDING)

web/views.py
from itertools import product
from django.shortcuts import render
from django.http import HttpResponse
from web.models import Product


def index(request):
    context = {
        "is_index" : True
    }
    return render(request, 'web/index.html',context)

  
def about(request):
    context = {
        "is_about" : True
    }
    return render(request, 'web/about_us.html',context)


def index_2(request):
    context = {
        "is_index_2" : True
    }
    return render(request, 'web/index_2.html',context)  


def blog(request):
    context = {
        "is_blog" : True
    }
    return render(request, 'web/blog.html',context)


def blogright(request):
    context = {
        "is_blogright" : True
    }
    return render(request, 'web/blog_right_sidebar.html',context)


def blogleft(request):
    context = {
        "is_blogleft" : True
    }
    return render(request, 'web/blog-left_sidebar.html',context)


def checkout(request):
    context = {
        "is_checkout" : True
    }
    return render(request, 'web/checkout_page.html',context)


def contact(request):
    context = {
        "is_contact" : True
    }
    return render(request, 'web/contact_page.html',context)


def wishlist(request):
    context = {
        "is_wishlist" : True
    }
    return render(request, 'web/my_wishlist.html',context)


def news(request):
    context = {
        "is_news" : True
    }
    return render(request, 'web/news_detalis.html',context)


def shopleft(request):
    context = {
        "is_shopleft" : True
    }
    return render(request, 'web/shop_detalis_left_sidebar.html',context)


def shopright(request):
    context = {
        "is_shopright" : True
    }
    return render(request, 'web/shop_detalis_right_sidebar.html',context)


def shopdetalis(request):
    context = {
        "products": Product.objects.all(),
        "is_shopdetalis" : True
    }
    return render(request, 'web/shop_detalis.html',context)


def shopdetalisleft(request):
    context = {
        "is_shopdetalisleft" : True
    }
    return render(request, 'web/shop_detalis_left_sidebar.html',context)


def shopdetalisright(request):
    context = {
        "is_shopdetalisright" : True
    }
    return render(request, 'web/shop_detalis_right_sidebar.html',context)


def shopgridleft(request):
    context = {
        "is_shopgridleft" : True
    }
    return render(request, 'web/shop_grid_left_sidebar.html',context)


def shopgridright(request):
    context = {
        "is_shopgridright" : True
    }
    return render(request, 'web/shop_grid_right_sidebar.html',context)    


def shopgrid(request):
    context = {
        "products": Product.objects.all(),
        "title" :"ashique",
        "is_shopgrid" : True
    }
    return render(request, 'web/shop_grid.html',context)


def error(request):
    context = {
        "is_error" : True
    }
    return render(request, 'web/404.html',context)


def shoplist(request):
    context = {
        "is_shoplist" : True
    }
    return render(request, 'web/shop_list.html',context)


def shoplistright(request):
    context = {
        "is_shoplistright" : True
    }
    return render(request, 'web/shop_list_right_sidebar.html',context)


def shoplistleft(request):
    context = {
        "is_shoplistleft" : True
    }
    return render(request, 'web/shop_list_left_sidebar.html',context)    
   

def shoppingcart(request):
    context = {
        "is_shoppingcart" : True
    }
    return render(request, 'web/shopping_cart.html',context)    
   

templates/includes/header.html
<!-- header area starts -->
<header>
  {% load static %}
    <div class="header-1 pt-35 ">
      <div class="container">
        <div class="row">
          <div class="col-xl-2 col-lg-2 col-md-6 col-sm-6 col-7 order-md-2 order-lg-1">
            <div class="logo text-md-center text-lg-left">
              <a href="{% url 'web:index' %}"><img src="{% static 'web/img/logo/logo.png' %}" alt="aruk-logo"></a>
            </div>
          </div>

          <div class="col-xl-7 col-lg-7 col-md-3 order-md-1 offset-sm-2 offset-md-0 order-lg-2 col-sm-auto">
            <nav>
              <div id="mobile-menu" class="main-menu">
                <ul>
                  <li>
                    <a href="{% url 'web:index' %}">Home</a>
                    <ul class="sub-menu pb-10 pt-10 pl-15 pr-15">
                      <li><a href="{% url 'web:index' %}">Home Style</a></li>
                      <li><a href="{% url 'web:index_2' %}">Home Style 2</a></li>
                    </ul>
                  </li>
                  <li>
                    <a href="{% url 'web:shopgrid' %}">Shop</a>
                    <ul class="sub-menu menu-level pb-10 pt-20 pl-15 pr-15">
                      <li>
                        <div>
                          <h4>Shop Grid</h4>
                          <ul class="sub-menu">

                            <li><a href="{% url 'web:shopgrid' %}">Shop Grid</a></li>
                            <li><a href="{% url 'web:shopgridleft' %}">Shop Grid LS</a></li>
                            <li><a href="{% url 'web:shopgridright' %}"> Shop Grid RS</a></li>
                          </ul>
                        </div>
                      </li>
                      <li>
                        <div>
                          <h4>Shop List</h4>
                          <ul class="sub-menu pb-10 pl-15 pr-15">
                            <li><a href="{% url 'web:shoplist' %}">Shop List</a></li>
                            <li><a href="{% url 'web:shoplistleft' %}">Shop List LS</a></li>
                            <li><a href="{% url 'web:shoplistright' %}">Shop List RS</a></li>

                          </ul>
                        </div>
                      </li>
                      <li>
                        <div>
                          <h4>Shop Details</h4>
                          <ul class="sub-menu pb-10 pl-15 pr-15">
                            <li><a href="{% url 'web:shopdetalis' %}">Shop Details</a></li>
                            <li><a href="{% url 'web:shopdetalisleft' %}">Shop Details LS</a></li>
                            <li><a href="{% url 'web:shopdetalisright' %}">Shop Details RS</a></li>
                          </ul>
                        </div>
                      </li>
                    </ul>
                  </li>
                  <li><a href="{% url 'web:shopgrid' %}">Collection</a></li>
                  <li><a href="#">Pages</a>
                    <ul class="sub-menu pb-10 pt-10 pl-15 pr-15">
                      <li><a href="{% url 'web:about' %}">About US</a></li>
                      <li><a href="{% url 'web:wishlist' %}">My Wishlist</a></li>
                      <li><a href="{% url 'web:shoppingcart' %}">Shopping Cart</a></li>
                      <li><a href="{% url 'web:checkout' %}">Checkout</a></li>
                      <li><a href="{% url 'web:news' %}">News Details</a></li>
                    </ul>
                  </li>
                  <li><a href="{% url 'web:blog' %}">Blog</a>
                    <ul class="sub-menu pb-10 pt-10 pl-15 pr-15">
                      <li><a href="{% url 'web:blog' %}">Blog</a></li>
                      <li><a href="{% url 'web:blogleft' %}">Blog LS</a></li>
                      <li><a href="{% url 'web:blogright' %}">Blog RS</a></li>
                    </ul>
                  </li>
                  <li><a href="{% url 'web:contact' %}">Contact</a></li>
                </ul>
              </div>
            </nav>
          </div>
          <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-5 order-md-3 order-lg-3 ">
            <div class="nav-icons">
              <ul>
                <li>
                  <div class="search position-relative">
                    <span ><i class="fas fa-search"></i></span>
                    <div class="search-overlap">
                    </div>
                    <form action="#" class="search-form position-fixed">
                      <div class="search-input ">
                        <div class="search-close">
                          <span>X</span>
                        </div>
                        <input type="text" placeholder="Enter your keywords.....">
                      </div>
                    </form>
                  </div>
                </li>
                <li><a href="{% url 'web:wishlist' %}"><i class="fas fa-shopping-cart"></i>
                    <span class="badge badge-pink ">1</span>
                  </a></li>{% url 'web:index' %}
                <li class="position-relative"><span class="product-cart"><i class="fas fa-user"></i></span>

                  <div class="product-on-sale pb-30">
                    <div class="product-close-icon">
                      <span>X</span>
                    </div>
                    <div class="product-wrapper d-flex">
                      <div class="product-img position-relative ">
                        <img src="{% static 'web/img/products/22.png' %}" alt="product">
                        <div class="cart-icon">
                          <a href="{% url 'web:shoppingcart' %}"><i class="las la-cart-plus"></i></a>
                        </div>
                      </div>
                      <div class="product-details mt-10">
                        <span>Shoes</span>
                        <h6><a href="{% url 'web:shopdetalis' %}">Leather Menz Shoes{% url 'web:index' %}</a></h6>
                        <div class="price d-flex">
                          <span>$999</span>
                          <del>$899</del>
                        </div>
                      </div>
                    </div>
                    <div class="product-wrapper mt-20 d-flex">
                      <div class="product-img position-relative">
                        <img src="{% static 'web/img/products/23.png' %}" alt="product">
                        <div class="cart-icon">
                          <a href="{% url 'web:shoppingcart' %}"><i class="las la-cart-plus"></i></a>
                        </div>
                      </div>
                      <div class="product-details mt-10">
                        <span>Shoes</span>
                        <h6><a href="{% url 'web:shopdetalis' %}">Leather Menz Shoes</a></h6>
                        <div class="price d-flex">
                          <span>$999</span>
                          <del>$899</del>
                        </div>
                      </div>
                    </div>
                    <div class="cart-price pr-20 pt-30">
                      <p>Subtotal: <span>$999.00</span></p>
                      <p>Total: <span>$999.00</span></p>
                    </div>
                    <div class="cart-button mt-20 pl-15">
                      <a  href="{% url 'web:shoppingcart' %}">View Cart</a>
                      <a  href="{% url 'web:checkout' %}">Checkout</a>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="mobile-menu"></div>
      </div>
    </div>
  </header>
  <!-- header area ends -->

templates/web/shop_list.html
{% extends 'web/base.html' %}
{% load static %}


{% block content %}
  <!-- =============Preloader Starts=============-->
  <div class="loader">
    <div class="face face-1">
      <div class="circle"></div>
    </div>
    <div class="face face-2">
      <div class="circle"></div>
    </div>
  </div>
  <!-- =============Preloader Ends=============-->

  <!-- header area starts -->

  {% include 'includes/header.html' %}
 
  <!-- header area ends -->
  <!-- Page Title Area Start -->
  <div class="page-title-area pt-150 pb-55">
    <div class="container">
      <div class="row">
        <div class="col-xl-12">
          <div class="page-titel-detalis  ">
            <div class="section-title">
              <h2>Shop List</h2>
            </div>
            <div class="page-bc">
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{% url 'web:index' %}">Home</a></li>
                  <li class="breadcrumb-item position-relative active" aria-current="page"><a
                      href="{% url 'web:shopgridright' %}">Shop List</a></li>
                </ol>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Page Title area Ends -->

  <!-- new arrival area starts -->
  <div class="shop-list shop-grid pt-120">
    <div class="container">
      <div class="row">
        <div class="col-xl-12 pb-50">
          <div class="toolbar-navi d-inline-block ">
            <div class="toolbar d-flex">
              <div class="sort-by  d-flex mr-30">
                <span class="mr-10 mt-5">Sort by :</span>
                <div class="sort-by-option option-list position-relative">
                  <button id="sort-option" class="option-dropdown">Most Recent <i class="fas fa-caret-down"></i></button>
  
                  <div id="sub-sort-option" class="sub-sort-option sub-option  position-absolute " >
                    <ul>
                      <li>
                        <span>Alphabet</span>
                      </li>
                      <li><span>Price</span></li>
                    </ul>
                  </div>
                </div>
  
              </div>
              <div class="show-option d-flex">
                <span class="mr-10 mt-5">Show :</span>
                <div class="show-option-list option-list position-relative">
                  <button id="show-option-numbe" class=" option-dropdown">11 <i class="fas fa-caret-down"></i></button>
                  <div id="sub-show-option" class="sub-show-option sub-option position-absolute" >
                    <ul>
                      <li><span>20</span></li>
                      <li><span>28</span></li>
                      <li><span>40</span></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="view-as d-flex ml-25">
                <ul class="view-as-button">
                  <li> <a href="{% url 'web:shopgrid' %}"><i class="fab fa-microsoft"></i></a></li>
                  <li> <a href="{% url 'web:shoplist' %}"><i class="fas fa-list-ul"></i></a></li>
                </ul>
  
              </div>
  
  
            </div>
          </div>
          <nav class="construction-pagination float-right" aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
              <li class="page-item">
                <a class="page-link" href="#"><i class="fas fa-chevron-left"></i></a>
              </li>
              <li class="page-item active">
                <a class="page-link" href="#">1</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">2</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">3</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#"><i class="fas fa-chevron-right"></i></a>
              </li>
            </ul>
          </nav>
        </div>
        <div class="col-xl-12">
          <div class="product-list new-arrival-2 new-arrival">
            <div class="product-wrapper mb-30">
              <div class="row">
                <div class="col-xl-8 col-lg-8 col-md-8">
                  <div class="arrival-items arrival-new-items d-flex position-relative">
                    <div class="arrival-img mt-50 ml-25 mb-50">
                      <img src="{% static 'web/img/products/01.png' %}" alt="bag">
                    </div>
                    <div class="arrival-details position-relative pt-75 ml-50">
                      <h5><a href="{% url 'web:shopdetalis' %}">Green Hand Bag</a></h5>
                      <ul class="rating pt-10">
                        <li><i class="las la-star"></i></li>
                        <li><i class="las la-star"></i></li>
                        <li><i class="las la-star"></i></li>
                        <li><i class="las la-star"></i></li>
                        <li><i class="las la-star"></i></li>
                      </ul>
                      <div class="materials pt-15">
                        <h6>Materials: <span>Plastic Body</span></h6>
                      </div>
                      <div class="product-color pt-10 d-flex">
                        <h6>Color:</h6>
                        <div class="color-code">
                          <span></span>
                          <span></span>
                        </div>
                      </div>
                      <div class="product-size d-flex pt-10">
                        <h6>Size: </h6>
                        <ul class="ml-5">
                          <li>Xl <span>|</span></li>
                          <li>L<span>|</span></li>
                          <li>M<span>|</span></li>
                          <li>S<span>|</span></li>
                          <li>XS</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-xl-4 col-lg-4 col-md-4">
                  <div class="buy-details text-center pt-95">
                    <span>$219.00</span>
                    <div class="delivery pt-15 pb-25">
                      <span><i class="las la-luggage-cart"></i>Free delivery US</span>
                    </div>
                    <div class="cart-button">
                      <a href="{% url 'web:shoppingcart' %}">Add to cart</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="product-wrapper mb-30">
              <div class="row">
                <div class="col-xl-8 col-lg-8 col-md-8">
                  <div class="arrival-items  d-flex position-relative">
                    <div class="arrival-img mt-50 ml-25 mb-50">
                      <img src="{% static 'web/img/products/5.png' %}" alt="Headset">
                    </div>
                    <div class="arrival-details position-relative pt-75 ml-50">
                      <h5><a href="{% url 'web:shopdetalis' %}">Kitty Electronic Headset</a></h5>
                      <ul class="rating pt-10">
                        <li><i class="las la-star"></i></li>
                        <li><i class="las la-star"></i></li>
                        <li><i class="las la-star"></i></li>
                        <li><i class="las la-star"></i></li>
                        <li><i class="las la-star"></i></li>
                      </ul>
                      <div class="materials pt-15">
                        <h6>Materials: <span>Plastic Body</span></h6>
                      </div>
                      <div class="product-color pt-10 d-flex">
                        <h6>Color:</h6>
                        <div class="color-code">
                          <span></span>
                          <span></span>
                        </div>
                      </div>
                      <div class="product-size d-flex pt-10">
                        <h6>Size: </h6>
                        <ul class="ml-5">
                          <li>Xl <span>|</span></li>
                          <li>L<span>|</span></li>
                          <li>M<span>|</span></li>
                          <li>S<span>|</span></li>
                          <li>XS</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-xl-4 col-lg-4 col-md-4">
                  <div class="buy-details text-center pt-95">
                    <span>$219.00</span>
                    <div class="delivery pt-15 pb-25">
                      <span><i class="las la-luggage-cart"></i>Free delivery US</span>
                    </div>
                    <div class="cart-button">
                      <a href="{% url 'web:shoppingcart' %}">Add to cart</a>
                    </div>
                  </div>
                </div>
              </div>
  
            </div>
            <div class="product-wrapper">
              <div class="row">
                <div class="col-xl-8 col-lg-8 col-md-8">
                  <div class="arrival-items  d-flex position-relative">
                    <div class="arrival-img mt-50 ml-25 mb-50">
                      <img src="{% static 'web/img/products/17.png' %}" alt="Wooden Ring">
                    </div>
                    <div class="arrival-details position-relative pt-75 ml-50">
                      <h5><a href="{% url 'web:shopdetalis' %}">Wooden Ring</a></h5>
                      <ul class="rating pt-10">
                        <li><i class="las la-star"></i></li>
                        <li><i class="las la-star"></i></li>
                        <li><i class="las la-star"></i></li>
                        <li><i class="las la-star"></i></li>
                        <li><i class="las la-star"></i></li>
                      </ul>
                      <div class="materials pt-15">
                        <h6>Materials: <span>Plastic Body</span></h6>
                      </div>
                      <div class="product-size d-flex pt-10">
                        <h6>Size: </h6>
                        <ul class="ml-5">
                          <li>Xl <span>|</span></li>
                          <li>L<span>|</span></li>
                          <li>M<span>|</span></li>
                          <li>S<span>|</span></li>
                          <li>XS</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-xl-4 col-lg-4 col-md-4">
                  <div class="buy-details text-center pt-95">
                    <span>$219.00</span>
                    <div class="delivery pt-15 pb-25">
                      <span><i class="las la-luggage-cart"></i>Free delivery US</span>
                    </div>
                    <div class="cart-button">
                      <a href="{% url 'web:shoppingcart' %}">Add to cart</a>
                    </div>
                  </div>
                </div>
              </div>
  
            </div>
          </div>
        </div>
        <div class="col-xl-12">
          <nav class="construction-pagination text-center pt-60" aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
              <li class="page-item">
                <a class="page-link" href="#"><i class="fas fa-chevron-left"></i></a>
              </li>
              <li class="page-item active">
                <a class="page-link" href="#">1</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">2</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">3</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#"><i class="fas fa-chevron-right"></i></a>
              </li>
            </ul>
          </nav>
          <div class="view-items text-center mt-60">
            <a class="p-btn position-relative" href="{% url 'web:shopgrid' %}">
            {% url 'web:shopgrid' %}ore</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- new arrival area ends -->


  <!-- Footer Area Starts -->
  {% endblock %}